name: Production deployment

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build.yml

  deployment:
    runs-on: ubuntu-latest
    environment: prod
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - name: Copy docker compose
        run:
          cp ./deploy/docker-compose.yaml ./docker-compose.yaml
        shell: bash
      - name: copy files to target server via scp
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          port: 22
          key: ${{ secrets.DEPLOY_KEY }}
          source: "./docker-compose.yaml"
          target: "/var/gallery/"
      - name: Run docker compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: docker compose -f /var/gallery/docker-compose.yaml up -d
